name: PR Set Up

on:
  # Run manually from the Actions tab:
  workflow_dispatch:

  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened

jobs:
  create_deployment:
    name: Create deployment
    runs-on: ubuntu-latest
    env:
      GOOGLE_CLOUD_SQL_INSTANCE: yorch-devs-staging
      DB_NAME: "myblog_pr${{ github.event.pull_request.number }}"

    # Generate a GitHub token that can be exchanged with Google Cloud - see
    # https://github.com/google-github-actions/auth/tree/v0.6.0#setting-up-workload-identity-federation
    permissions:
      contents: read
      id-token: write

    steps:
      # actions/checkout MUST come before auth
      - name: Checkout the code
        uses: actions/checkout@v3.1.0

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1.0.0
        with:
          service_account: yorch-devs-staging@yorch-devs-staging.iam.gserviceaccount.com
          workload_identity_provider: projects/833586262248/locations/global/workloadIdentityPools/yorch-devs-staging-pool/providers/github

      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v1.0.0

      - name: Ensure a review database exists
        run: |-
          gcloud sql databases describe ${{ env.DB_NAME }} \
            --instance=${{ env.GOOGLE_CLOUD_SQL_INSTANCE }} \
            --format="value(name)" \
          && echo "Database ${{ env.DB_NAME }} already exists" \
          || gcloud sql databases create ${{ env.DB_NAME }} \
            --instance=${{ env.GOOGLE_CLOUD_SQL_INSTANCE }}
