name: CI/CD Staging

on:
  # Trigger the workflow on pushes to the main branch, including PR merges:
  push:
    branches:
      - main

# Generate a GitHub token that can be exchanged with Google Cloud - see
# https://github.com/google-github-actions/auth/tree/v0.6.0#setting-up-workload-identity-federation
permissions:
  contents: read
  id-token: write
  deployments: write

jobs:
  test-and-build:
    name: Integration
    uses: ./.github/workflows/test-and-build.yml
    secrets: inherit

  deploy-to-gcp:
    name: Deploy to GCP
    uses: ./.github/workflows/cloud-run.yml
    needs:
      - test-and-build
    with:
      environment: staging
      deploy-name: staging
      cloud-sql-instance: yorch-devs-staging:us-central1:yorch-devs-staging
      cloud-sql-username-secret: db-username:latest
      cloud-sql-password-secret: db-password:latest
      cloud-run-service-suffix: ${{ needs.test-and-build.outputs.git-commit-short-sha }}
      cloud-run-container-image: us-central1-docker.pkg.dev/yorch-devs-staging/myblog/myblog@${{ needs.test-and-build.outputs.container-image-digest }}
    secrets: inherit
